### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by melatawy** [AnthonyCalandra/todo-list#11]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by AnthonyCalandra** [comment]
This is now resolved in v1.1.0.

**Comment by joshschumacher** [comment]
When do you plan on cutting the v1.1.0 release with these fixes? I see a couple of comments about a v1.1.0 release but it looks like the most most recent tag is v1.0.0

**Comment by AnthonyCalandra** [comment]
@joshschumacher I realize development has been kind of slow lately, but I'm working on the other 3 bugs brought up and the PR; will package them all in the 1.1.0 release. No ETA yet. :(
